version: '3'
services:
  frontend:
    image: joi292/sre-frontend:v1
    ports:
    - "8080:8080"
    volumes:
    - frontend-volume:/frontend
    networks:
    - frontend-app
  backend:
    image: joi292/backend-python:v1
    ports:
    - "5000:5000"
    volumes:
    - backend-volume:/backend
    networks:
    - frontend-app
  nginx:
    image: joi292/nginx-proxy:v1
    ports:
    - "80:80"
    volumes: 
    - nginx_html:/usr/share/nginx/html/
    networks:
    - frontend-app

volumes:
  frontend-volume:
  backend-volume:
  nginx_html:

networks:
 frontend-app:
